In [2]:
import numpy as np

In [2]:
lst = [[1,2,3],
       [1,2,3]]

In [3]:
type(lst)

list

In [4]:
arr = np.array(lst)

In [5]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

2

In [8]:
arr.size

6

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr.shape

(2, 3)

In [11]:
zeroes = np.zeros((2,4))

In [12]:
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ones = np.ones((2,3))

In [14]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

# Random Number Generating

In [19]:
arr = np.random.random((3,2))

In [16]:
np.random.random()

0.6575797826095554

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [26]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [23]:
arr = np.reshape(arr, (2,3))

In [24]:
arr

array([[0.86328179, 0.36243566, 0.19327225],
       [0.76172881, 0.1291398 , 0.27242302]])

In [25]:
arr.flatten()

array([0.86328179, 0.36243566, 0.19327225, 0.76172881, 0.1291398 ,
       0.27242302])

# Arithmetic Operations

In [30]:
arr = np.array([1,2,3,4,5,6])

In [31]:
arr

array([1, 2, 3, 4, 5, 6])

In [32]:
print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 2)
print(arr ** 2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[ 1  4  9 16 25 36]


In [33]:
arr.max()

6

In [34]:
arr.min()

1

In [35]:
arr.sum()

21

In [37]:
arr2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [38]:
arr2.max(axis = 0)

array([7, 8, 9])

In [39]:
arr2.max(axis = 1)

array([3, 6, 9])

In [40]:
arr2.min(axis = 0)

array([1, 2, 3])

In [41]:
arr2.min(axis = 1)

array([1, 4, 7])

In [42]:
arr2.sum()

45

# Array Sorting Methods

In [47]:
arr = np.array([[7,3,8,6,4],
                [7,2,9,8,6],
                [5,4,2,3,1]])

In [48]:
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [49]:
np.sort(arr, axis = 1, kind = 'mergesort')

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [50]:
np.sort(arr, axis = 0, kind = 'mergesort')

array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

# Array Merging & Splitting

In [51]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[7,8,9],
                 [10,11,12]])

In [58]:
arr = np.vstack((arr1,arr2))

In [53]:
np.vstack((arr2, arr1))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [54]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [55]:
np.hstack((arr2,arr1))

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [56]:
np.concatenate((arr1,arr2), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
np.concatenate((arr1,arr2), axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [59]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
np.vsplit(arr,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

# Indexing, Slicing & Cropping

In [63]:
arr = np.array([1,2,3,4,5,6,7,8])

In [64]:
arr[1]

2

In [66]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
arr[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [68]:
arr[-2]

7

In [69]:
arr[: -2]

array([1, 2, 3, 4, 5, 6])

In [70]:
arr[2 : -2]

array([3, 4, 5, 6])

In [71]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [72]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [73]:
arr[: , :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [74]:
arr[1: , :]

array([[5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [75]:
arr[:1 , :]

array([[1, 2, 3, 4]])

In [76]:
arr[:1]

array([[1, 2, 3, 4]])

In [77]:
arr[1: , 1:]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

# Automate using Numpy

In [78]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [79]:
c = 0

for i in lst:
    if i > 5:
        c += 1

print(c)

5


In [80]:
lst = np.array(lst)

In [81]:
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

In [83]:
lst[lst % 3 == 0]

array([3, 6, 9])

In [84]:
len(lst[lst % 3 == 0])

3

In [93]:

array1 = np.array([[1, 2, 3, 4, 5],[20,30,40,50,60]])
array2 = np.array ([[6, 7, 8, 9, 10],[9,8,7,6,5]])
array1 = np.column_stack([array1, array2])
print(array1)

[[ 1  2  3  4  5  6  7  8  9 10]
 [20 30 40 50 60  9  8  7  6  5]]


In [ ]:
array1.sort()

# Mean, Variance and Standard Deviation

In [10]:
arr = np.random.randint(1,10,10)
print(arr)

[1 5 8 9 2 7 3 3 2 4]


In [11]:
print(arr.mean())

4.4


In [12]:
print(arr.std())

2.6153393661244038


In [13]:
print(arr.var())

6.839999999999999


# Transpose of an Array

In [14]:
arr = np.random.randint(1,15, (3,4))
print(arr)

[[11  6  9  2]
 [14 11  9 12]
 [ 8  9 12  2]]


In [15]:
print(arr.T)

[[11 14  8]
 [ 6 11  9]
 [ 9  9 12]
 [ 2 12  2]]


# Where 

In [16]:
arr = np.random.randint(1,100,10)

print(arr)

[80 49 38 21 95 50 22 79 29 55]


In [18]:
arr1 = np.where(arr%2 == 0, 'even', arr)
arr1 = np.where(arr%2 != 0, 'odd', arr1)
print(arr1)

['even' 'odd' 'even' 'odd' 'odd' 'even' 'even' 'odd' 'odd' 'odd']
